services:

  user-service:
    build:
      context: ./user-service
    ports:
      - "8080:8080"

  listing-service:
    build:
      context: ./listing-service
    ports:
      - "6000:6000"

  public-api:
    build:
      context: ./public-api
    ports:
      - "8888:8080"
    depends_on:
      - user-service
      - listing-service
